CREATE TYPE OT$_99_LOV_CUR_LST AS OBJECT
 (  id        VARCHAR2(30),
    dsc       VARCHAR2(500),
    lcc_yn    VARCHAR2(1),
    ius_yn    VARCHAR2(1),
    unt_dsc   VARCHAR2(100),
    sunt_dsc  VARCHAR2(100),
   CONSTRUCTOR FUNCTION OT$_99_LOV_CUR_LST RETURN SELF AS RESULT)
/

CREATE TYPE BODY OT$_99_LOV_CUR_LST IS
  CONSTRUCTOR FUNCTION OT$_99_LOV_CUR_LST RETURN SELF AS RESULT IS
  BEGIN
    RETURN;
  END;
END;
/
   
CREATE TYPE OT$_99_LOV_CUR_LST_TB AS TABLE OF OT$_99_LOV_CUR_LST
/