--
-- Connect as SYSTEM OR SYS 
--
--
-- Change "SCHEMA_NAME" to actual Schema name
--

GRANT CREATE SESSION TO SCHEMA_NAME WITH ADMIN OPTION;
GRANT CREATE SEQUENCE TO SCHEMA_NAME;
GRANT CREATE TABLE TO SCHEMA_NAME;
GRANT CREATE VIEW TO SCHEMA_NAME;
GRANT CREATE JOB TO SCHEMA_NAME;
GRANT CREATE TRIGGER TO SCHEMA_NAME;
GRANT CREATE MATERIALIZED VIEW TO SCHEMA_NAME;
GRANT CREATE ANY VIEW TO SCHEMA_NAME;
GRANT CREATE ANY TYPE TO SCHEMA_NAME;
GRANT CREATE ANY CONTEXT TO SCHEMA_NAME;
GRANT CREATE PROCEDURE TO SCHEMA_NAME;
GRANT CREATE ANY SYNONYM TO SCHEMA_NAME;
GRANT CREATE USER TO SCHEMA_NAME;
GRANT ALTER USER TO SCHEMA_NAME;
GRANT DROP USER TO SCHEMA_NAME;
GRANT CREATE DATABASE LINK TO SCHEMA_NAME;
GRANT EXP_FULL_DATABASE TO SCHEMA_NAME;
GRANT IMP_FULL_DATABASE TO SCHEMA_NAME;
GRANT IMPORT FULL DATABASE TO SCHEMA_NAME;
GRANT EXPORT FULL DATABASE TO SCHEMA_NAME;
GRANT APEX_ADMINISTRATOR_ROLE TO SCHEMA_NAME;
GRANT EXECUTE ON APEX_INSTANCE_ADMIN TO SCHEMA_NAME;
GRANT ALTER SYSTEM TO SCHEMA_NAME;
GRANT SELECT ANY DICTIONARY TO SCHEMA_NAME;
GRANT CREATE ANY DIRECTORY TO SCHEMA_NAME;
GRANT SELECT ANY SEQUENCE TO SCHEMA_NAME;
GRANT SELECT ANY TABLE TO SCHEMA_NAME;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO SCHEMA_NAME;
GRANT EXECUTE ON SYS.UTL_SMTP TO SCHEMA_NAME;
GRANT EXECUTE ON SYS.UTL_TCP TO SCHEMA_NAME;
GRANT EXECUTE ON SYS.UTL_FILE TO SCHEMA_NAME;
GRANT EXECUTE ON SYS.DBMS_SESSION TO SCHEMA_NAME;
GRANT EXECUTE ON SYS.DBMS_BACKUP_RESTORE TO SCHEMA_NAME;
GRANT EXECUTE ON SYS.DBMS_NETWORK_ACL_ADMIN TO SCHEMA_NAME;
CREATE OR REPLACE FORCE VIEW SYS.V_99_KRBMSFT
(FILE_NM, FILE_STMP, FILE_SZ)
AS
SELECT fname_krbmsft AS file_nm,
       stamp_krbmsft AS file_stmp,
       size_krbmsft AS file_sz
FROM   x$krbmsft;
GRANT SELECT ON SYS.V_99_KRBMSFT TO SCHEMA_NAME;
GRANT EXECUTE ON SYS.DBMS_BACKUP_RESTORE TO SCHEMA_NAME;