-- USER MAINTENANCE RECORD
CREATE OR REPLACE VIEW V_99_99_UMR
 ( P_K,
   R_S,
   USR_KY,
   USR_ID,
   FIR_NM,
   LST_NM,
   RPT_NM,
   GDR_DM,
   GDR_DSC,
   TTL_DSC,
   EML_ADR,
   PRM_PHN,
   USR_DM,
   USR_DSC,
   EDT_YN,
   VRF_YN,
   APR_YN,
   LGP_KY,
   LGP_DSC,
   STA_DSC,
   LIN_DT_DSC,
   LIN_CNT,
   CPW_DT_DSC,
   CPW_CNT,   
   OTH_RMK,
   AU_INS_UNM,
   AU_INS_TMD,
   AU_APR_UNM,
   AU_APR_TMD,
   AU_UPD_UNM,
   AU_UPD_TMD   ) 
AS SELECT 
   C100   P_K,
   N1     R_S,
   N38    USR_KY,
   C100   USR_ID,
   C50    FIR_NM,
   C50    LST_NM,
   C30    RPT_NM,
   C10    GDR_DM,
   C50    GDR_DSC,
   C50    TTL_DSC,
   C250   EML_ADR,
   C100   PRM_PHN,
   C10    USR_DM,
   C50    USR_DSC,
   N1     EDT_YN,
   N1     VRF_YN,
   N1     APR_YN,
   N38    LGP_KY,
   C100   LGP_DSC,
   C50    STA_DSC,
   C50    LIN_DT_DSC,
   N38    LIN_CNT,
   C50    CPW_DT_DSC,
   N38    CPW_CNT,   
   C500   OTH_RMK,
   C100   AU_INS_UNM,
   C100   AU_INS_TMD,
   C100   AU_APR_UNM,
   C100   AU_APR_TMD,
   C100   AU_UPD_UNM,
   C100   AU_UPD_TMD    
 FROM T_99_00_STC 
 WHERE ROWNUM < 1 ;
 
CREATE OR REPLACE VIEW V_99_99_UMR_E
AS SELECT  P_K,
           R_S,
           USR_KY,
           USR_ID,
           FIR_NM,
           LST_NM,
           RPT_NM,
           GDR_DM,
           TTL_DSC,
           EML_ADR,
           PRM_PHN,
           USR_DM,
           EDT_YN,
           VRF_YN,
           APR_YN,
           LGP_KY,
           OTH_RMK 
FROM V_99_99_UMR;

CREATE OR REPLACE VIEW V_99_99_UMR_P
AS SELECT  P_K,
           R_S,
           USR_KY,
           USR_DM,
           EDT_YN,
           VRF_YN,
           APR_YN,
           LGP_KY
FROM V_99_99_UMR;

           