@@pk$990_spec.sql
@@PK99_ATH_spec.sql
@@PK99_TRG_spec.sql
@@PKWF_99_001_spec.sql
@@PKWF_99_ACP_spec.sql
@@PKWF_99_ACS_spec.sql
@@PKWF_99_ATC_spec.sql
@@PKWF_99_ATH_spec.sql
@@PKWF_99_CUR_spec.sql
@@PKWF_99_DMV_spec.sql
@@PKWF_99_DTM_spec.sql
@@PKWF_99_EML_ITF_spec.sql
@@PKWF_99_EML_MSG_spec.sql
@@PKWF_99_EML_PMR_spec.sql
@@PKWF_99_EML_SND_spec.sql
@@PKWF_99_EML_SPEC.sql
@@PKWF_99_ERR_spec.sql
@@PKWF_99_GEN_spec.sql
@@PKWF_99_GLB_spec.sql
@@PKWF_99_GU1_spec.sql
@@PKWF_99_NCR_spec.sql
@@PKWF_99_PMR_spec.sql
@@PKWF_99_PWM_spec.sql
@@PKWF_99_SSI_spec.sql
@@PKWF_99_SSS_spec.sql
@@PKWF_99_SWM_spec.sql
@@PKWF_99_TRG_spec.sql
@@PKWF_99_UMA_spec.sql
@@PKWF_99_UMC_spec.sql
@@PKWF_99_VLD_spec.sql
@@PKWF_99_VPD_spec.sql
@@PKWF_99_XCP_spec.sql
