CREATE TYPE OT$_99_LOV_ID AS OBJECT
 (  id	VARCHAR2(100),
    dsc	VARCHAR2(500),
   CONSTRUCTOR FUNCTION OT$_99_LOV_ID RETURN SELF AS RESULT)
/

CREATE TYPE BODY OT$_99_LOV_ID IS
  CONSTRUCTOR FUNCTION OT$_99_LOV_ID RETURN SELF AS RESULT IS
  BEGIN
    RETURN;
  END;
END;
/
   
CREATE TYPE OT$_99_LOV_ID_TB AS TABLE OF OT$_99_LOV_ID
/