@@pkwf_00_00_dmv_spec.sql
@@pkwf_00_00_err_spec.sql
@@pkwf_00_00_spec.sql
@@pkwf_00_acl_spec.sql
@@pkwf_00_apx_spec.sql
@@pkwf_00_ath_spec.sql
@@pkwf_00_dsp_spec.sql
@@pkwf_00_flx_spec.sql
@@pkwf_00_jsn_spec.sql
@@pkwf_00_pdf_spec.sql
@@pkwf_00_pmr_spec.sql
@@pkwf_00_spec.sql
@@pkwf_00_vld_spec.sql
@@pkwf_01_eml_spec.sql
@@pkwf_10_eml_spec.sql
@@pkwf_10_mb_spec.sql
@@pkwf_10_rl_mb_spec.sql
@@pkwf_10_rl_spec.sql
@@pkwf_11_mb_spec.sql
@@pkwf_11_rl_spec.sql
@@pkwf_20_gen_spec.sql
@@pkwf_30_am_if_mnd_spec.sql
@@pkwf_30_am_mf_rdm_spec.sql
@@pkwf_30_ch_wdr_spec.sql
@@pkwf_30_cs_new_c_spec.sql
@@pkwf_30_cs_new_j_spec.sql
@@pkwf_30_cs_new_spec.sql
@@pkwf_30_cs_reg_2_spec.sql
@@pkwf_30_cs_reg_spec.sql
@@pkwf_30_gen_spec.sql
@@pkwf_30_ws_spec.sql
@@pkwf_89_cs_spec.sql
@@pkwf_89_st_spec.sql
@@pkwf_90_alt_spec.sql
@@pkwf_90_gen_spec.sql
