CREATE OR REPLACE VIEW wf_vi_30_cs_new_j
AS
SELECT DC.ROW_KEY,
       DC.D_ID,
       DC.DC_TP_K,  
       DC.DC_ID,
       DC.DC_DTT,
       DC.DC_ST_DM,
       DC.DC_JSN,
       DC.DC_LNK_YN,
       DC.DC_LNK_K,
       --
       -- PRIMARY
       DM01    TT_DM,
       SDC01   LS_NM,
       LID01   MD_NM,
       LID02   FI_NM,
       DM02    GDR_DM,
       D01     DOB_DT,
       DM03    MAR_ST_DM,
       SID01   NTY_CD,
       LDC01   PRY_A_AD1,
       LDC02   PRY_A_AD2,
       LID03   PRY_A_CTY,
       SID02   PRY_A_STA_CD,
       LID04   PRY_A_ZIP,
       SID03   PRY_A_CTR_CD,
       LDC03   PST_A_AD1,
       LDC04   PST_A_AD2,
       LID05   PST_A_CTY,
       SID04   PST_A_STA_CD,
       LID06   PST_A_ZIP,
       SID05   PST_A_CTR_CD,
       SDC02   PRY_EM_AD,
       SDC03   SEC_EM_AD,
       LID07   MBL_PHN,
       LID08   OTH_PHN,
       SDC04   MMD_NM,
       LDC05   NOK_NM,
       SID15   NOK_RLN_CD,
       LID09   NOK_PHN,
       LDC06   NOK_A_AD1,
       LDC07   NOK_A_AD2,
       LID10   NOK_A_CTY,
       SID06   NOK_A_STA_CD,
       LID11   NOK_A_ZIP,
       SID07   NOK_A_CTR_CD,
       SDC05   BK_NM,
       LID12   BK_AC_NO,
       LID13   BK_BV_NO,
       SDC06   BK_AC_NM,
       SDC07   BK_BR_NM,
       LID14   BK_ST_CD,
       LDC08   BK_A_AD1,
       LDC09   BK_A_AD2,
       LID15   BK_A_CTY,
       SID08   BK_A_STA_CD,
       LID16   BK_A_ZIP,
       SID09   BK_A_CTR_CD,
       SDC08   OCP_NM,
       LDC10   EMP_NM,
       LDC11   EMP_A_AD1,
       LDC12   EMP_A_AD2,
       LID23   EMP_A_CTY,
       SID13   EMP_A_STA_CD,
       LID24   EMP_A_ZIP,
       SID14   EMP_A_CTR_CD,
       LID17   EMP_PHN,
       M01     ANN_INC_AMT,
       DM04    MDL_ID,
       LID18   PDT_ID,
       SDC13   PDT_DSC,
       --
       DM07    C_PIC_YN,
       BL01    PIC_IMG,
       DM08    C_SIG_YN,
       BL02    SIG_IMG,
       DM09    C_UBL_YN,
       BL03    UBL_IMG,
       DM10    C_IDC_YN,
       BL04    IDC_IMG,
       --
       -- SECONDARY
       DM01    J_TT_DM,
       SDC01   J_LS_NM,
       LID01   J_MD_NM,
       LID02   J_FI_NM,
       DM02    J_GDR_DM,
       D01     J_DOB_DT,
       DM03    J_MAR_ST_DM,
       SID01   J_NTY_CD,
       LDC01   J_PRY_A_AD1,
       LDC02   J_PRY_A_AD2,
       LID03   J_PRY_A_CTY,
       SID02   J_PRY_A_STA_CD,
       LID04   J_PRY_A_ZIP,
       SID03   J_PRY_A_CTR_CD,
       LDC03   J_PST_A_AD1,
       LDC04   J_PST_A_AD2,
       LID05   J_PST_A_CTY,
       SID04   J_PST_A_STA_CD,
       LID06   J_PST_A_ZIP,
       SID05   J_PST_A_CTR_CD,
       SDC02   J_PRY_EM_AD,
       SDC03   J_SEC_EM_AD,
       LID07   J_MBL_PHN,
       LID08   J_OTH_PHN,
       SDC04   J_MMD_NM,
       LDC05   J_NOK_NM,
       SID15   J_NOK_RLN_CD,
       LID09   J_NOK_PHN,
       LDC06   J_NOK_A_AD1,
       LDC07   J_NOK_A_AD2,
       LID10   J_NOK_A_CTY,
       SID06   J_NOK_A_STA_CD,
       LID11   J_NOK_A_ZIP,
       SID07   J_NOK_A_CTR_CD,
       SDC05   J_BK_NM,
       LID12   J_BK_AC_NO,
       LID13   J_BK_BV_NO,
       SDC06   J_BK_AC_NM,
       SDC07   J_BK_BR_NM,
       LID14   J_BK_ST_CD,
       LDC08   J_BK_A_AD1,
       LDC09   J_BK_A_AD2,
       LID15   J_BK_A_CTY,
       SID08   J_BK_A_STA_CD,
       LID16   J_BK_A_ZIP,
       SID09   J_BK_A_CTR_CD,
       SDC08   J_OCP_NM,
       LDC10   J_EMP_NM,
       LDC11   J_EMP_A_AD1,
       LDC12   J_EMP_A_AD2,
       LID23   J_EMP_A_CTY,
       SID13   J_EMP_A_STA_CD,
       LID24   J_EMP_A_ZIP,
       SID14   J_EMP_A_CTR_CD,
       LID17   J_EMP_PHN,
       M01     J_ANN_INC_AMT,
       --
       DM07    J_C_PIC_YN,
       BL01    J_PIC_IMG,
       DM08    J_C_SIG_YN,
       BL02    J_SIG_IMG,
       DM09    J_C_UBL_YN,
       BL03    J_UBL_IMG,
       DM10    J_C_IDC_YN,
       BL04    J_IDC_IMG,
       --
       SDC11   MKT_ACT_ID,
       SDC12   MKT_CHN_NO
  FROM wf_30_dc dc
 WHERE d_id = 'WFVI30CSNEWJ'
/
