CREATE OR REPLACE VIEW wf_vi_30_cs_new
AS
SELECT DC.ROW_KEY,
       DC.D_ID,
       DC.DC_TP_K,  
       DC.DC_ID,
       DC.DC_DTT,
       DC.DC_ST_DM,
       DC.DC_JSN,
       DC.DC_LNK_YN,
       DC.DC_LNK_K,
       --
       DM01    TT_DM,
       SDC01   LS_NM,
       LID01   MD_NM,
       LID02   FI_NM,
       DM02    GDR_DM,
       D01     DOB_DT,
       DM03    MAR_ST_DM,
       SID01   NTY_CD,
       LDC01   PRY_A_AD1,
       LDC02   PRY_A_AD2,
       LID03   PRY_A_CTY,
       SID02   PRY_A_STA_CD,
       LID04   PRY_A_ZIP,
       SID03   PRY_A_CTR_CD,
       LDC03   PST_A_AD1,
       LDC04   PST_A_AD2,
       LID05   PST_A_CTY,
       SID04   PST_A_STA_CD,
       LID06   PST_A_ZIP,
       SID05   PST_A_CTR_CD,
       SDC02   PRY_EM_AD,
       SDC03   SEC_EM_AD,
       LID07   MBL_PHN,
       LID08   OTH_PHN,
       SDC04   MMD_NM,
       LDC05   NOK_NM,
       SID15   NOK_RLN_CD,
       LID09   NOK_PHN,
       LDC06   NOK_A_AD1,
       LDC07   NOK_A_AD2,
       LID10   NOK_A_CTY,
       SID06   NOK_A_STA_CD,
       LID11   NOK_A_ZIP,
       SID07   NOK_A_CTR_CD,
       SDC05   BK_NM,
       LID12   BK_AC_NO,
       LID13   BK_BV_NO,
       SDC06   BK_AC_NM,
       SDC07   BK_BR_NM,
       LID14   BK_ST_CD,
       LDC08   BK_A_AD1,
       LDC09   BK_A_AD2,
       LID15   BK_A_CTY,
       SID08   BK_A_STA_CD,
       LID16   BK_A_ZIP,
       SID09   BK_A_CTR_CD,
       SDC08   OCP_NM,
       LDC10   EMP_NM,
       LDC11   EMP_A_AD1,
       LDC12   EMP_A_AD2,
       LID23   EMP_A_CTY,
       SID13   EMP_A_STA_CD,
       LID24   EMP_A_ZIP,
       SID14   EMP_A_CTR_CD,
       LID17   EMP_PHN,
       M01     ANN_INC_AMT,
       DM04    MDL_ID,
       LID18   PDT_ID,
       SDC13   PDT_DSC,
       --
       LID19   C_PIC_YN,
       BL01    PIC_IMG,
       LID20   C_SIG_YN,
       BL02    SIG_IMG,
       LID21   C_UBL_YN,
       BL03    UBL_IMG,
       LID22   C_IDC_YN,
       BL04    IDC_IMG,
       --
       SDC11   MKT_ACT_ID,
       SDC12   MKT_CHN_NO
  FROM wf_30_dc dc
 WHERE d_id = 'WFVI30CSNEW'
/
