CREATE OR REPLACE VIEW wf_vr_30_cs_new
AS
SELECT dc.row_key,
       dc.d_id,
       dc.dc_tp_k,  
       tp.tp_id,
       tp.tp_dsc,
       dc.dc_id,
       dc.dc_dtt,
       dc.dc_st_dm,
       dc.dc_jsn,
       dc.tt_dm,
       dc.ls_nm,
       dc.md_nm,
       dc.fi_nm,
       dc.gdr_dm,
       pkwf_00_00_dmv.fn_cs_gdr_dsc(dc.gdr_dm) gdr_dm_dsc,
       dc.dob_dt,
       dc.mar_st_dm,
       pkwf_00_00_dmv.fn_cs_mar_dsc(dc.mar_st_dm) mar_st_dm_dsc,
       dc.nty_cd,
       pkwf_00_00.fn_get_nty_dsc(dc.nty_cd) nty_cd_dsc,
       dc.pry_a_ad1,
       dc.pry_a_ad2,
       dc.pry_a_cty,
       dc.pry_a_sta_cd,
       pkwf_00_00.fn_get_sta_dsc(dc.pry_a_sta_cd) pry_a_sta_cd_dsc,
       dc.pry_a_zip,
       dc.pry_a_ctr_cd,
       pkwf_00_00.fn_get_ctr_dsc(dc.pry_a_ctr_cd) pry_a_ctr_cd_dsc,
       dc.pst_a_ad1,
       dc.pst_a_ad2,
       dc.pst_a_cty,
       dc.pst_a_sta_cd,
       pkwf_00_00.fn_get_sta_dsc(dc.pst_a_sta_cd) pst_a_sta_cd_dsc,
       dc.pst_a_zip,
       dc.pst_a_ctr_cd,
       pkwf_00_00.fn_get_ctr_dsc(dc.pst_a_ctr_cd) pst_a_ctr_cd_dsc,
       dc.pry_em_ad,
       dc.sec_em_ad,
       dc.mbl_phn,
       dc.oth_phn,
       dc.mmd_nm,
       dc.nok_nm,
       dc.nok_phn,
       dc.nok_a_ad1,
       dc.nok_a_ad2,
       dc.nok_a_cty,
       dc.nok_a_sta_cd,
       pkwf_00_00.fn_get_sta_dsc(dc.nok_a_sta_cd) nok_a_sta_cd_dsc,
       dc.nok_a_zip,
       dc.nok_a_ctr_cd,
       pkwf_00_00.fn_get_ctr_dsc(dc.nok_a_ctr_cd) nok_a_ctr_cd_dsc,
       dc.bk_nm,
       dc.bk_ac_no,
       dc.bk_bv_no,
       dc.bk_ac_nm,
       dc.bk_br_nm,
       dc.bk_st_cd,
       dc.bk_a_ad1,
       dc.bk_a_ad2,
       dc.bk_a_cty,
       dc.bk_a_sta_cd,
       pkwf_00_00.fn_get_sta_dsc(dc.bk_a_sta_cd) bk_a_sta_cd_dsc,
       dc.bk_a_zip,
       dc.bk_a_ctr_cd,
       pkwf_00_00.fn_get_ctr_dsc(dc.bk_a_ctr_cd) bk_a_ctr_cd_dsc,
       dc.ocp_nm,
       dc.emp_nm,
    --   'PLEASE REMOVE USE PROPER ADDRESS FIELDS' emp_adr,
       dc.emp_a_ad1,
       dc.emp_a_ad2,
       dc.emp_a_cty,
       dc.emp_a_sta_cd,
       pkwf_00_00.fn_get_sta_dsc(dc.emp_a_sta_cd) emp_a_sta_cd_dsc,
       dc.emp_a_zip,
       dc.emp_a_ctr_cd,
       pkwf_00_00.fn_get_ctr_dsc(dc.emp_a_ctr_cd) emp_a_ctr_cd_dsc,
       dc.emp_phn,
       dc.ann_inc_amt,
       NULL jnt_yn, --dc.jnt_yn,
       NULL j_tt_dm, --dc.j_tt_dm,
       NULL j_ls_nm, --dc.j_ls_nm,
       NULL j_md_nm, --dc.j_md_nm,
       NULL j_fi_nm, --dc.j_fi_nm,
       NULL j_gdr_dm, --dc.j_gdr_dm,
       NULL j_gdr_dm_dsc, --pkwf_00_00_dmv.fn_cs_gdr_dsc(dc.j_gdr_dm) j_gdr_dm_dsc,
       NULL j_dob_dt, --dc.j_dob_dt,
       NULL j_nty_cd, --dc.j_nty_cd,
       NULL j_nty_cd_dsc, --pkwf_00_00.fn_get_nty_dsc(dc.j_nty_cd) j_nty_cd_dsc,
       NULL j_pry_a_ad1, --dc.j_pry_a_ad1,
       NULL j_pry_a_ad2, --dc.j_pry_a_ad2,
       NULL j_pry_a_cty, --dc.j_pry_a_cty,
       NULL j_pry_a_sta_cd, --dc.j_pry_a_sta_cd,
       NULL j_pry_a_sta_cd_dsc, --pkwf_00_00.fn_get_sta_dsc(dc.j_pry_a_sta_cd) j_pry_a_sta_cd_dsc,
       NULL j_pry_a_zip, --dc.j_pry_a_zip,
       NULL j_pry_a_ctr_cd, --dc.j_pry_a_ctr_cd,
       NULL j_pry_a_ctr_cd_dsc, --pkwf_00_00.fn_get_ctr_dsc(dc.j_pry_a_ctr_cd) j_pry_a_ctr_cd_dsc,
       NULL j_pry_em_ad,--dc.j_pry_em_ad,
       NULL j_mbl_phn, --dc.j_mbl_phn,
       dc.c_pic_yn,
       dc.pic_img,
       dc.c_sig_yn,
       dc.sig_img,
       dc.c_ubl_yn,
       dc.ubl_img,
       dc.c_idc_yn,
       dc.idc_img
  FROM wf_vi_30_cs_new dc, wf_10_tp tp
 WHERE dc.dc_tp_k = tp.row_key;
/
