CREATE OR REPLACE VIEW wf_vr_30_cs_new_j
AS
SELECT dc.row_key,
       dc.d_id,
       dc.dc_tp_k,  
       tp.tp_id,
       tp.tp_dsc,
       dc.dc_id,
       dc.dc_dtt,
       dc.dc_st_dm,
       dc.dc_jsn,
       -- Primary Applicant
       dc.tt_dm,
       dc.ls_nm,
       dc.md_nm,
       dc.fi_nm,
       dc.gdr_dm,
       pkwf_00_00_dmv.fn_cs_gdr_dsc(dc.gdr_dm) gdr_dm_dsc,
       dc.dob_dt,
       dc.mar_st_dm,
       pkwf_00_00_dmv.fn_cs_mar_dsc(dc.mar_st_dm) mar_st_dm_dsc,
       dc.nty_cd,
       pkwf_00_00.fn_get_nty_dsc(dc.nty_cd) nty_cd_dsc,
       dc.pry_a_ad1,
       dc.pry_a_ad2,
       dc.pry_a_cty,
       dc.pry_a_sta_cd,
       pkwf_00_00.fn_get_sta_dsc(dc.pry_a_sta_cd) pry_a_sta_cd_dsc,
       dc.pry_a_zip,
       dc.pry_a_ctr_cd,
       pkwf_00_00.fn_get_ctr_dsc(dc.pry_a_ctr_cd) pry_a_ctr_cd_dsc,
       dc.pst_a_ad1,
       dc.pst_a_ad2,
       dc.pst_a_cty,
       dc.pst_a_sta_cd,
       pkwf_00_00.fn_get_sta_dsc(dc.pst_a_sta_cd) pst_a_sta_cd_dsc,
       dc.pst_a_zip,
       dc.pst_a_ctr_cd,
       pkwf_00_00.fn_get_ctr_dsc(dc.pst_a_ctr_cd) pst_a_ctr_cd_dsc,
       dc.pry_em_ad,
       dc.sec_em_ad,
       dc.mbl_phn,
       dc.oth_phn,
       dc.mmd_nm,
       dc.nok_nm,
       dc.nok_rln_cd,
       pkwf_00_00.fn_get_rln_dsc(dc.nok_rln_cd) nok_rln_cd_dsc,
       dc.nok_phn,
       dc.nok_a_ad1,
       dc.nok_a_ad2,
       dc.nok_a_cty,
       dc.nok_a_sta_cd,
       pkwf_00_00.fn_get_sta_dsc(dc.nok_a_sta_cd) nok_a_sta_cd_dsc,
       dc.nok_a_zip,
       dc.nok_a_ctr_cd,
       pkwf_00_00.fn_get_ctr_dsc(dc.nok_a_ctr_cd) nok_a_ctr_cd_dsc,
       dc.bk_nm,
       dc.bk_ac_no,
       dc.bk_bv_no,
       dc.bk_ac_nm,
       dc.bk_br_nm,
       dc.bk_st_cd,
       dc.bk_a_ad1,
       dc.bk_a_ad2,
       dc.bk_a_cty,
       dc.bk_a_sta_cd,
       pkwf_00_00.fn_get_sta_dsc(dc.bk_a_sta_cd) bk_a_sta_cd_dsc,
       dc.bk_a_zip,
       dc.bk_a_ctr_cd,
       pkwf_00_00.fn_get_ctr_dsc(dc.bk_a_ctr_cd) bk_a_ctr_cd_dsc,
       dc.ocp_nm,
       dc.emp_nm,
       dc.emp_a_ad1,
       dc.emp_a_ad2,
       dc.emp_a_cty,
       dc.emp_a_sta_cd,
       pkwf_00_00.fn_get_sta_dsc(dc.emp_a_sta_cd) emp_a_sta_cd_dsc,
       dc.emp_a_zip,
       dc.emp_a_ctr_cd,
       pkwf_00_00.fn_get_ctr_dsc(dc.emp_a_ctr_cd) emp_a_ctr_cd_dsc,
       dc.emp_phn,
       dc.ann_inc_amt,
       --
       -- Joint Applicant
       dc.j_tt_dm,
       dc.j_ls_nm,
       dc.j_md_nm,
       dc.j_fi_nm,
       dc.j_gdr_dm,
       pkwf_00_00_dmv.fn_cs_gdr_dsc(dc.j_gdr_dm) j_gdr_dm_dsc,
       dc.j_dob_dt,
       dc.j_mar_st_dm,
       pkwf_00_00_dmv.fn_cs_mar_dsc(dc.j_mar_st_dm) j_mar_st_dm_dsc,
       dc.j_nty_cd,
       pkwf_00_00.fn_get_nty_dsc(dc.j_nty_cd) j_nty_cd_dsc,
       dc.j_pry_a_ad1,
       dc.j_pry_a_ad2,
       dc.j_pry_a_cty,
       dc.j_pry_a_sta_cd,
       pkwf_00_00.fn_get_sta_dsc(dc.j_pry_a_sta_cd) j_pry_a_sta_cd_dsc,
       dc.j_pry_a_zip,
       dc.j_pry_a_ctr_cd,
       pkwf_00_00.fn_get_ctr_dsc(dc.j_pry_a_ctr_cd) j_pry_a_ctr_cd_dsc,
       dc.j_pst_a_ad1,
       dc.j_pst_a_ad2,
       dc.j_pst_a_cty,
       dc.j_pst_a_sta_cd,
       pkwf_00_00.fn_get_sta_dsc(dc.j_pst_a_sta_cd) j_pst_a_sta_cd_dsc,
       dc.j_pst_a_zip,
       dc.j_pst_a_ctr_cd,
       pkwf_00_00.fn_get_ctr_dsc(dc.j_pst_a_ctr_cd) j_pst_a_ctr_cd_dsc,
       dc.j_pry_em_ad,
       dc.j_sec_em_ad,
       dc.j_mbl_phn,
       dc.j_oth_phn,
       dc.j_mmd_nm,
       dc.j_nok_nm,
       dc.j_nok_rln_cd,
       pkwf_00_00.fn_get_rln_dsc(dc.j_nok_rln_cd) j_nok_rln_cd_dsc,
       dc.j_nok_phn,
       dc.j_nok_a_ad1,
       dc.j_nok_a_ad2,
       dc.j_nok_a_cty,
       dc.j_nok_a_sta_cd,
       pkwf_00_00.fn_get_sta_dsc(dc.j_nok_a_sta_cd) j_nok_a_sta_cd_dsc,
       dc.j_nok_a_zip,
       dc.j_nok_a_ctr_cd,
       pkwf_00_00.fn_get_ctr_dsc(dc.j_nok_a_ctr_cd) j_nok_a_ctr_cd_dsc,
       dc.j_bk_nm,
       dc.j_bk_ac_no,
       dc.j_bk_bv_no,
       dc.j_bk_ac_nm,
       dc.j_bk_br_nm,
       dc.j_bk_st_cd,
       dc.j_bk_a_ad1,
       dc.j_bk_a_ad2,
       dc.j_bk_a_cty,
       dc.j_bk_a_sta_cd,
       pkwf_00_00.fn_get_sta_dsc(dc.j_bk_a_sta_cd) j_bk_a_sta_cd_dsc,
       dc.j_bk_a_zip,
       dc.j_bk_a_ctr_cd,
       pkwf_00_00.fn_get_ctr_dsc(dc.j_bk_a_ctr_cd) j_bk_a_ctr_cd_dsc,
       dc.j_ocp_nm,
       dc.j_emp_nm,
       dc.j_emp_a_ad1,
       dc.j_emp_a_ad2,
       dc.j_emp_a_cty,
       dc.j_emp_a_sta_cd,
       pkwf_00_00.fn_get_sta_dsc(dc.j_emp_a_sta_cd) j_emp_a_sta_cd_dsc,
       dc.j_emp_a_zip,
       dc.j_emp_a_ctr_cd,
       pkwf_00_00.fn_get_ctr_dsc(dc.j_emp_a_ctr_cd) j_emp_a_ctr_cd_dsc,
       dc.j_emp_phn,
       dc.j_ann_inc_amt,
       --
       -- Images
       im.pic_img pic_img,
       im.pic_sgn sig_img,
       im.pic_usr idc_img,
       im.pic_utl ubl_img,
       im.pic_img_j pic_img_j,
       im.pic_sgn_j sig_img_j,
       im.pic_usr_j idc_img_j,
       im.pic_utl_j ubl_img_j,
       --
       p.pdt_id,
       p.pdt_dsc
  FROM wf_vi_30_cs_new_j dc, 
       wf_10_tp tp,
       wf_vp_30_cs_new_im_j im,
       wf_v_00_dc_pdt p
 WHERE dc.dc_tp_k = tp.row_key 
   AND dc.row_key = im.dc_k
   AND dc.dc_id = p.dc_id;
/
